#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server using `scp`

if [ $# != 4 ]
then
	str="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	echo $str
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
