#!/usr/bin/env bash
# A Bash script that installs nginx on web-01 server, listen at port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html
# printf %s "server {
#        listen  80 default_server;
#        listen  [::]:80 default_server;
#        root    /etc/nginx/html;
#        index   index.html index.htm;
# }">/etc/nginx/sites-available/default

service nginx start
