#!/usr/bin/env bash
# A Bash script that configures an Nginx server so that
# /redirect_me redirects to another page.
# And the redirection is configured as a "301 Moved Permanently"

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
# printf %s "server {
#        listen  80 default_server;
#        listen  [::]:80 default_server;
#        root    /etc/nginx/html;
#        index   index.html index.htm;
# }">/etc/nginx/sites-available/default
redir="location /redirect_me {\nreturn 301 http://www.youtube.com/watch?v=AZg4uJkEa-4&feature=youtu.be&hd=1;\n}\n"
sudo sed -i "30i $redir" /etc/nginx/sites-available/default

sudo service nginx restart
