#!/usr/bin/env bash
# A bash Script that Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page

sudo apt-get -y update
sudo apt-get -y install nginx

sudo bash -c "echo 'Hello World!' > /etc/nginx/html/index.html"
service nginx start

redir="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=AZg4uJkEa-4&feature=youtu.be&hd=1;\n}\n"
sudo sed -i "30i $redir" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
redir2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\n}\n"
sudo sed -i "30i $redir2" /etc/nginx/sites-available/default

sudo service nginx restart
