#!/usr/bin/env bash
# A bash script that configures a brand new Ubuntu machine to the asked requirements

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /etc/nginx/html/index.html
service nginx start

redir="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=AZg4uJkEa-4&feature=youtu.be&hd=1;\n}\n"
sudo sed -i "30i $redir" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/custom_404.html
redir2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /etc/nginx/html;\ninternal;\nq}\n"
sudo sed -i "30i $redir2" /etc/nginx/sites-available/default
sudo sed -i "21i add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
