#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# But for the 9th iteration, displays "Best School"
# and then "Hi" on a new line

i=0
while [ $i -ne 10 ]
do
	i=$((i+1))
	if [ $i -eq 10 ]
	then
		echo "Hi"
	fi
	echo "Best School"
done
