#!/usr/bin/env bash
# A bash script that displays "Best School" 10 times
# Displays "bad luck" for the 4th loop iteration
# Displays "good luck" for the 8th loop iteration
# Displays "Best School" for the other iterations

i=0
while [ $i -ne 10 ]
do
	i=$((i+1))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
