#!/usr/bin/env bash
# A bash script that configures an Ubuntu server with the below requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sudo echo "127.0.0.2	localhost">~/hosts.new
sudo echo "8.8.8.8	facebook.com">>~/hosts.new
cp -f ~/host.new /etc/hosts
